services:
  file-server:
    container_name: file-server
    build: .
    restart: unless-stopped
    volumes:
      - ./ssh:/root/.ssh
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASS=${SAMBA_PASS}
    ports:
      - "${BIND_IP}:445:445"
