services:
  file-server:
    container_name: file-server
    build: .
    restart: unless-stopped
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASS=${SAMBA_PASS}
    ports:
      - "445:445"
